---
title: "hw10"
author: "Scott Karr"
date: "April 1, 2016"
output: html_document
---
library(jsonlite)
library(httr)
library(stringr)
library(plyr)
#semantic search
semantic_key <- "&api-key=621746db4c8f966bdf1f67dca6aa3b90:13:65002889"
url <- "http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_per/Gillis,%20Justin.json?fields=all"
json_file <- paste0(url, semantic_key)
json_data_raw <- fromJSON(json_file)

#review meta-data 
names(json_data_raw)
df_nyt_meta <- data.frame(
  c(status = unlist(json_data_raw[1])),
  c(copyright = unlist(json_data_raw[2])),
  c(num_results = unlist(json_data_raw[3]))
)

#...nested lists into data frame
names(json_data_raw$results)
df_article_bodies <- data.frame(json_data_raw$results$article_list$results[[1]][[1]])
df_article_nytd_des <- data.frame(unlist(json_data_raw$results$article_list$results[[1]][[3]]$nytd_des))
df_article_nytd_geo <- data.frame(unlist(json_data_raw$results$article_list$results[[1]][[3]]$nytd_geo))
df_results<-data.frame(json_data_raw[['results']])
df_geocodes <- data.frame(json_data_raw[[4]][[11]])

